# Generated by Django 3.1.5 on 2021-01-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Love story', max_length=256),
            preserve_default=False,
        ),
    ]
