# Generated by Django 3.1.5 on 2021-01-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_auto_20210124_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Forum.post'),
        ),
    ]
